resolver: lts-14.7
packages:
- my-xmonad
nix:
  path: [ "nixpkgs=https://github.com/NixOS/nixpkgs/archive/e6b93257b0ba070bd12810eeacbe281396c24316.tar.gz" ]
  add-gc-roots: true
  packages:
  - zlib
  - x11
  - xorg.libXrandr
  - xorg.libXScrnSaver
  - xorg.libXrender

