name:                my-xmonad
version:             0.0.0.0
github:              "NorfairKing/my-xmonad"
author:              "Tom Sydney Kerckhove"
maintainer:          "syd@cs-syd.eu"
copyright:           "2019 Tom Sydney Kerckhove"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - containers
  - optparse-applicative
  - xmonad
  - xmonad-contrib

executables:
  xmonad:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - my-xmonad
